import type { ChromeStrings } from "./types";

export const de: ChromeStrings = {
  notifications: "Benachrichtigungen",
  markAllRead: "alle gelesen",
  caughtUp: "Alles gelesen",
  openChangelog: "→ Changelog öffnen",
  markRead: "als gelesen",
  delete: "löschen",
  newVersion: (v) => `Neue Version ${v}`,
  newVersionBody: "Es gibt Neuerungen — wirf einen Blick in den Changelog.",
  shuttingDown: "herunterfahren …",
  pressPowerToBoot: "Power drücken zum Starten",
  unlockHint: "Klick oder Taste drücken zum Entsperren",
  kernelPanic: "Kernel Panic — alles ist weg",
  confirmReboot: "System neu starten?",
  confirmShutdown: "System herunterfahren?",
  systemWillRestart: "Das System wird neu gestartet.",
  systemWillPowerOff: "Das System wird ausgeschaltet.",
  reopenWindows: "Fenster danach wieder öffnen",
  cancel: "Abbrechen",
  reboot: "Neustarten",
  shutdown: "Herunterfahren",
  noWindows: "keine Fenster offen",
  dangerZone: "⚠ Gefahrenzone — root",
  dangerDesc: "Alle Einstellungen vergessen, alles löschen und sauber neu starten.",
  factoryReset: "Werksreset",
  cookie: {
    title: "cookie-notice.sh",
    command: "cat privacy",
    line1: "Diese Seite verwendet Cookies bzw. lokale Speicherung.",
    line2: "Details siehe Datenschutzerklärung.",
    output: "→ OK.",
    accept: "Verstanden",
    details: "Details",
  },
  settings: {
    design: "Design", theme: "Theme", themeSystem: "System", themeLight: "Hell", themeDark: "Dunkel",
    primaryColour: "Primärfarbe", pride: "Pride", on: "An", off: "Aus", motionNote: "Animationen folgen deiner Systemeinstellung „Bewegung reduzieren“.",
    about: "Über", version: "Version", build: "Build", browser: "Browser", platform: "Plattform", screen: "Bildschirm",
    checking: "suche…", checkUpdates: "nach Updates suchen", upToDate: "ist aktuell ✓", releaseNotes: "Versionshinweise",
    language: "Sprache", klingonHint: "Klingonisch schaltet auch ein bedrohliches Theme.",
    mature: "Inhalte für Erwachsene", matureDesc: "Blendet als „mature“ markierte Inhalte frei.",
  },
  terminal: {
    helpHint: "type `help` · <tab> completes",
    availableCommands: "verfügbare Befehle:",
    runHelp: "'<befehl> --help' für Details",
    unknownCommand: "Befehl nicht gefunden",
    notFound: "nicht gefunden",
    permissionDenied: "Zugriff verweigert — sudo verwenden",
    usageSudo: "Verwendung: sudo <befehl>",
    noHistory: "(keine Historie)",
    historyCleared: "Historie gelöscht",
    themeChanged: (v) => `theme → ${v}`,
    accentChanged: (v) => `accent → ${v}`,
    prideChanged: (on) => `pride ${on ? "an 🏳️‍🌈" : "aus"}`,
    rebooting: "wird neu gestartet …",
    shuttingDownCmd: "wird heruntergefahren …",
    resetting: "wird auf Werkseinstellungen zurückgesetzt …",
    versionLine: (v, b) => `Version ${v} · Build ${b}`,
    loadAverage: "Systemlast (1m · 5m · 15m)",
    motd: "Willkommen zurück.",
    missingOperand: "fehlendes Argument",
    removed: (id) => `entfernt: ${id}`,
    nothingToRemove: "nichts zu entfernen",
    viewHint: "ist ein Fenster — mit 'open' öffnen",
    noSuchDirectory: "kein solches Verzeichnis",
    switchingTo: (locale) => `wechsle zu ${locale.toUpperCase()} …`,
    opening: (id) => `öffne ${id} …`,
    noItems: "(nichts vorhanden)",
    empty: "(leer)",
    alreadyRemoved: "bereits entfernt",
    isDirectory: "ist ein Verzeichnis",
    readOnly: "schreibgeschützt (Link)",
    suGranted: (user, host) => `${user}@${host} ist jetzt root — 'exit' zum Zurückwechseln.`,
    suDropped: "zurück zur normalen Shell.",
  },
};
