import type { ChromeStrings } from "./types";

export const en: ChromeStrings = {
  notifications: "Notifications",
  markAllRead: "mark all read",
  caughtUp: "You're all caught up",
  openChangelog: "→ open changelog",
  markRead: "mark read",
  delete: "delete",
  newVersion: (v) => `New version ${v}`,
  newVersionBody: "There are updates — take a look at the changelog.",
  shuttingDown: "shutting down …",
  pressPowerToBoot: "press power to boot",
  unlockHint: "click or press any key to unlock",
  kernelPanic: "kernel panic — everything is gone",
  confirmReboot: "Reboot system?",
  confirmShutdown: "Shut down system?",
  systemWillRestart: "The system will restart.",
  systemWillPowerOff: "The system will power off.",
  reopenWindows: "Reopen windows afterwards",
  cancel: "Cancel",
  reboot: "Reboot",
  shutdown: "Shut down",
  noWindows: "no windows open",
  dangerZone: "⚠ danger zone — elevated",
  dangerDesc: "Forget every setting, wipe and reboot into a clean state.",
  factoryReset: "Factory reset",
  cookie: {
    title: "cookie-notice.sh",
    command: "cat privacy",
    line1: "This site uses cookies or local storage.",
    line2: "See the privacy policy for details.",
    output: "→ OK.",
    accept: "Got it",
    details: "Details",
  },
  settings: {
    design: "Design", theme: "Theme", themeSystem: "System", themeLight: "Light", themeDark: "Dark",
    primaryColour: "Primary colour", pride: "Pride", on: "On", off: "Off", motionNote: "Animations follow your system's “reduce motion” setting.",
    about: "About", version: "Version", build: "Build", browser: "Browser", platform: "Platform", screen: "Screen",
    checking: "checking…", checkUpdates: "check for updates", upToDate: "is up to date ✓", releaseNotes: "release notes",
    language: "Language", klingonHint: "Klingon is a full menacing theme too.",
    mature: "Mature content", matureDesc: "Reveals content flagged as mature.",
  },
  terminal: {
    helpHint: "type `help` · <tab> completes",
    availableCommands: "available commands:",
    runHelp: "run '<command> --help' for details",
    unknownCommand: "command not found",
    notFound: "not found",
    permissionDenied: "permission denied — use sudo",
    usageSudo: "usage: sudo <command>",
    noHistory: "(no history)",
    historyCleared: "history cleared",
    themeChanged: (v) => `theme → ${v}`,
    accentChanged: (v) => `accent → ${v}`,
    prideChanged: (on) => `pride ${on ? "on 🏳️‍🌈" : "off"}`,
    rebooting: "rebooting …",
    shuttingDownCmd: "shutting down …",
    resetting: "resetting to factory defaults …",
    versionLine: (v, b) => `version ${v} · build ${b}`,
    loadAverage: "load average (1m · 5m · 15m)",
    motd: "Welcome back.",
    missingOperand: "missing operand",
    removed: (id) => `removed: ${id}`,
    nothingToRemove: "nothing to remove",
    viewHint: "is a window — use 'open' to view it",
    noSuchDirectory: "no such directory",
    switchingTo: (locale) => `switching to ${locale.toUpperCase()} …`,
    opening: (id) => `opening ${id} …`,
    noItems: "(no items)",
    empty: "(empty)",
    alreadyRemoved: "already removed",
    isDirectory: "is a directory",
    readOnly: "read-only (link)",
    suGranted: (user, host) => `${user}@${host} is now root — type 'exit' to drop back.`,
    suDropped: "dropped back to the user shell.",
  },
};
