import type { ChromeStrings } from "./types";

// Klingon overlay for ToOS's own chrome vocabulary (flavour text, not a
// rigorous translation — see locales/klingon.ts on the consumer side for the
// same convention applied to site content).
export const klingon: ChromeStrings = {
  notifications: "ja'chuqmey",
  markAllRead: "Hoch laD",
  caughtUp: "Hoch bIlaDpu'",
  openChangelog: "→ mIw qon yIlaD",
  markRead: "laD",
  delete: "chIp",
  newVersion: (v) => `chu' ${v}`,
  newVersionBody: "chu' tu'lu' — mIw qon yIlaD.",
  shuttingDown: "SoQtaH …",
  pressPowerToBoot: "HoS batlh yIchu'",
  unlockHint: "yIchu' pagh Doch yIlaD",
  kernelPanic: "pat Hegh — Hoch chIp",
  confirmReboot: "pat DachenmoH'a'?",
  confirmShutdown: "pat DaSoQmoH'a'?",
  systemWillRestart: "pat chu' taH.",
  systemWillPowerOff: "pat SoQtaH.",
  reopenWindows: "chaH cheghmoH",
  cancel: "yIbel",
  reboot: "chu'moH",
  shutdown: "SoQmoH",
  noWindows: "chaH pagh",
  dangerZone: "⚠ Seng Daq — pIn'a'",
  dangerDesc: "Hoch qeD lIj bIlIjHa'; pat chu' taH.",
  factoryReset: "pat chu'moH",
  cookie: {
    title: "cookie-QIn.sh",
    command: "cat pegh",
    line1: "Qu'vam cookie lo'taH — chaq De' pol.",
    line2: "pegh chut Daq De' latlh.",
    output: "→ maj.",
    accept: "jIyaj",
    details: "De' latlh",
  },
  settings: {
    design: "rItlh", theme: "rItlh", themeSystem: "pat", themeLight: "wov", themeDark: "Hurgh",
    primaryColour: "wa'DIch rItlh", pride: "batlh", on: "chu'", off: "SoQ", motionNote: "vIH lu'ta' qo'lIj rItlh.",
    about: "'oH", version: "chu'", build: "chenmoH", browser: "De'wI' mach", platform: "pat", screen: "mIllogh",
    checking: "nejtaH…", checkUpdates: "chu' nej", upToDate: "Qapla' ✓", releaseNotes: "De' chu'",
    language: "Hol", klingonHint: "tlhIngan Hol — batlh rItlh je!",
    mature: "loD De'", matureDesc: "loD De' rItlh yIchu'.",
  },
  terminal: {
    helpHint: "`help` yIlaD · <tab> ta'",
    availableCommands: "ra'mey tu'lu':",
    runHelp: "'<ra'> --help' yIlaD",
    unknownCommand: "ra' tu'lu'be'",
    notFound: "tu'lu'be'",
    permissionDenied: "ngeHbe' — sudo yIlo'",
    usageSudo: "yIlo': sudo <ra'>",
    noHistory: "(qon Hutlh)",
    historyCleared: "qon chIp",
    themeChanged: (v) => `rItlh → ${v}`,
    accentChanged: (v) => `rItlh → ${v}`,
    prideChanged: (on) => `batlh ${on ? "chu' 🏳️‍🌈" : "SoQ"}`,
    rebooting: "chu'moHtaH …",
    shuttingDownCmd: "SoQtaH …",
    resetting: "pat chu'moHtaH …",
    versionLine: (v, b) => `chu' ${v} · chenmoH ${b}`,
    loadAverage: "Qu' 'ugh (1m · 5m · 15m)",
    motd: "yIchegh.",
    missingOperand: "Doch Hutlh",
    removed: (id) => `chIp: ${id}`,
    nothingToRemove: "pagh chIp",
    viewHint: "SIrmey — 'open' yIlo'",
    noSuchDirectory: "Daq tu'lu'be'",
    switchingTo: (locale) => `${locale.toUpperCase()} Daq jItlhap …`,
    opening: (id) => `${id} yIpoS …`,
    noItems: "(pagh tu'lu')",
    empty: "(chIm)",
    alreadyRemoved: "chIppu'",
    isDirectory: "Daq 'oH",
    readOnly: "ghItlhlaHbe'",
    suGranted: (user, host) => `${user}@${host} pIn'a' DaH — 'exit' yIlo' bIchegh.`,
    suDropped: "Human De'wI' Daq bIcheghpu'.",
  },
};
