export type ChromeStrings = {
  notifications: string;
  markAllRead: string;
  caughtUp: string;
  openChangelog: string;
  markRead: string;
  delete: string;
  newVersion: (v: string) => string;
  newVersionBody: string;
  shuttingDown: string;
  pressPowerToBoot: string;
  unlockHint: string;
  kernelPanic: string;
  confirmReboot: string;
  confirmShutdown: string;
  systemWillRestart: string;
  systemWillPowerOff: string;
  reopenWindows: string;
  cancel: string;
  reboot: string;
  shutdown: string;
  noWindows: string;
  dangerZone: string;
  dangerDesc: string;
  factoryReset: string;
  cookie: { title: string; command: string; line1: string; line2: string; output: string; accept: string; details: string };
  settings: {
    design: string; theme: string; themeSystem: string; themeLight: string; themeDark: string;
    primaryColour: string; pride: string; on: string; off: string; motionNote: string;
    about: string; version: string; build: string; browser: string; platform: string; screen: string;
    checking: string; checkUpdates: string; upToDate: string; releaseNotes: string;
    language: string; klingonHint: string;
    mature: string; matureDesc: string;
  };
  terminal: {
    helpHint: string;
    availableCommands: string;
    runHelp: string;
    unknownCommand: string;
    notFound: string;
    permissionDenied: string;
    usageSudo: string;
    noHistory: string;
    historyCleared: string;
    themeChanged: (v: string) => string;
    accentChanged: (v: string) => string;
    prideChanged: (on: boolean) => string;
    rebooting: string;
    shuttingDownCmd: string;
    resetting: string;
    versionLine: (v: string, b: string) => string;
    loadAverage: string;
    motd: string;
    missingOperand: string;
    removed: (id: string) => string;
    nothingToRemove: string;
    viewHint: string;
    noSuchDirectory: string;
    switchingTo: (locale: string) => string;
    opening: (id: string) => string;
    noItems: string;
    empty: string;
    alreadyRemoved: string;
    isDirectory: string;
    readOnly: string;
    suGranted: (user: string, host: string) => string;
    suDropped: string;
  };
};
